version: "3.5"

volumes:
  redis_data:
    name: demo-03-redis

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  app:
    container_name: app
    build:
      context: .
    environment:
      - REDIS_HOST=redis
    image: 03-nodejs-redis
    ports:
      - "3000:3000"
