schema_version: v1.0.0
environment:
    name: Dev-eks-base
    description: Dev environment for EKS-base
    revision:
        type: branch
        identifier: pranay/VAN-3958
        repo: https://github.com/cldcvr/codepipes-tutorials
        dir: /tfs/aws-eks-vpc
        driver: github
    tfVersion: 1.3.7
