schema_version: v1.0.0
deployment:
    name: cloudrun
    deploymentConfig:
        artifact:
            id: e62dc1cf-ba35-4eef-833e-64f5de36a314
            containerImage:
                reference: latest
        template:
            moduleRefId: gcp:cloud-run@1
            inputs:
                allowUnauthenticated: true
                containerPort: 8080
                domain: ""
                region: us-central1
                vpcConnector: ${terraform.connector_name.value}
        env:
            IMAGE_PATH: test.gif
application:
    import: app-borat.yaml
environment:
    import: environment-my-env.yaml
