schema_version: v1.0.0
environment:
    name: my-env
    revision:
        type: branch
        identifier: pranay/VAN-2729
        repo: https://github.com/cldcvr/codepipes-tutorials
        dir: /dependency-demo/networkTemplate
        driver: github
    tfVersion: 1.2.5
