schema_version: v1.0.0
environment:
    name: development
    revision:
        type: branch
        identifier: tempBranch
        repo: https://github.com/cldcvr/codepipes-tutorials
        dir: dependency-demo/borat-gcs-redis/infra
        driver: github
    tfVersion: 1.2.5
