schema_version: v1.0.0
environment:
    name: development
    revision:
        type: branch
        identifier: main
        repo: https://github.com/cldcvr/codepipes-tutorials
        dir: dependency-demo/borat-gcs-redis/infra
        driver: github
    tfVersion: 1.2.5
    variables:
    - type: tf_var
      key: GOOGLE_PROJECT
      value: pranay-test-dev
