schema_version: v1.0.0
environment:
    name: development
    revision:
        type: branch
        identifier: shekhar/VAN-4215
        repo: https://github.com/cldcvr/codepipes-tutorials
        dir: dependency-demo/borat-s3-env-provider/infra
        driver: github
    policySet: Unrestricted

