schema_version: v1.0.0
environment:
    name: development
    revision:
        type: branch
        identifier: main
        repo: https://github.com/ollionorg/codepipes-tutorials
        dir: dependency-demo/borat-s3-env-provider/infra
        driver: github
    policySet: Unrestricted

