schema_version: v1.0.0
environment:
    name: dev
    revision:
        type: branch
        identifier: main
        repo: https://github.com/cldcvr/codepipes-tutorials
        dir: helm-example/infra/gke
        driver: github
    variables:
        - key: project_id
          value: pranay-test-dev
          type: tf_var
        - key: location
          value: asia-southeast1
          type: tf_var
