schema_version: v1.0.0
deployment:
    name: ngnix-helm-app-dev
    deploymentConfig:
        artifact:
            id: 5af03e36-550d-4f71-afe2-7430273697ac
            gitCode:
                type: branch
                identifier: main
        template:
            moduleRefId: gcp:basic-helm@1
            inputs:
                cluster: ${terraform.cluster.value}
                deployment_timeout: 300s
                helm_chart_name: nginx
                helm_chart_repo: bitnami
                helm_chart_url: https://charts.bitnami.com/bitnami
                helm_chart_version: ""
                helm_values_path: ""
                namespace: default
                region: ${terraform.region.value}
application:
    import: app-helm-app.yaml
environment:
    import: environment-dev.yaml
