schema_version: v1.0.0
deployment:
    name: banking-app-prod
    deploymentConfig:
        artifact:
            id: eac84f49-6b31-4c03-85b8-7bf3a07f4627
            containerImage:
                reference: v1.0.0
        template:
            moduleRefId: aws:app-runner@1
            inputs:
                cpu: 1 vCPU
                ecr_role: ${terraform.ecr_role.value}
                instance_role: ${terraform.instance_role.value}
                is_public: true
                memory: 2 GB
                port: 3000
                region: ${terraform.aws_region.value}
                vpc_connector_arn: ${terraform.vpc_connector.value}
        env:
            DB_SSLMODE: disable
application:
    import: app-banking-app.yaml
environment:
    import: environment-prod-AppRunner-Base.yaml
