schema_version: v1.0.0
environment:
    name: Dev-AppRunner-Base
    description: dev environment for AppRunner-Base
    revision:
        type: branch
        identifier: main
        repo: https://github.com/cldcvr/codepipes-tutorials
        dir: /tfs/aws-ecr-apprunner-vpc
        driver: github
    tfVersion: 1.3.7
