schema_version: v1.0.0
environment:
    name: Prod-AppRunner-Base
    description: prod environment for AppRunner-Base
    revision:
        type: branch
        identifier: main
        repo: https://github.com/ollionorg/codepipes-tutorials
        dir: /tfs/aws-ecr-apprunner-vpc
        driver: github
    tfVersion: 1.3.7
