schema_version: v0.0.1

environment:
  import: ./env.yml

application:
  import: ./voteApp.yml

deployment:
  name: VoteDeployment
  description: Vote Service Deployment
  deploymentConfig:
    artifact:
      id: 3e9f0abf-c768-499d-8c46-577777222dc
    template:
      moduleRefId: aws:basic-eks-regional@1
      inputs:
        cluster: "${terraform.cluster_name.value}"
        region:  "${terraform.cluster_region.value}"
        roleArn:  "${terraform.eks_arn.value}"
        ports:
          -  name: "vote"
             containerPort: 80
             protocol: "TCP"
             healthCheck: "/health"
        ingress:
          - domain: codepipes.tk
            certificateArn: "$certificateArn"
            appDomain: voting.codepipes.tk
            externalDNSenabled: "true"
    env:
      PG_HOST: "${terraform.rds_instance_address.value}"
      REDIS_HOST: "${terraform.redis_hostname.value}"
      certificateArn: "${terraform.certificate_arn.value}"
    summary:
      - name: Service URL
        command: echo https://$(kubectl get ingress -n voting-app -o=jsonpath='{.items[*].metadata.annotations.external-dns\.alpha\.kubernetes\.io\/hostname}')
