schema_version: v1.0.0
deployment:
    name: world-lambda-container-dev-world-1
    deploymentConfig:
        artifact:
            id: f0edd504-a66b-4110-84e5-aa413cdcef79
            containerImage:
                reference: latest
        template:
            moduleRefId: aws:lambda-gateway-container@1
            inputs:
                architecture: x86_64
                bucket: codepipes-assets
                function: world
                memory: "1024"
                path: /world
                region: us-east-1
                timeout: 10
                verb: GET
application:
    import: app-world-lambda-container.yaml
environment:
    import: environment-dev.yaml
