schema_version: v1.0.0
deployment:
    name: hello-lambda-container-dev-hello-1
    deploymentConfig:
        artifact:
            id: b5cd97bf-c689-4032-a78c-116aeb01b682
            containerImage:
                reference: latest
        template:
            moduleRefId: aws:lambda-gateway-container@1
            inputs:
                architecture: x86_64
                bucket: codepipes-assets
                function: hello
                memory: "1024"
                path: /hello
                region: us-east-1
                timeout: 10
                verb: GET
application:
    import: app-hello-lambda-container.yaml
environment:
    import: environment-dev.yaml
