schema_version: v1.0.0
deployment:
    name: go-code-lambda
    deploymentConfig:
        artifact:
            id: 9bcb92de-403a-4df6-8983-03f6080a4221
            gitCode:
                type: branch
                identifier: main
        template:
            moduleRefId: aws:lambda-gateway-code@1
            inputs:
                bucket: codepipes-assets
                funcs:
                    - handler: bin/hello
                      name: hello
                      path: /hello
                      verb: GET
                    - handler: bin/world
                      name: world
                      path: /world
                      verb: GET
                region: us-east-1
                runtime: go1.x
application:
    import: app-lambda-go-code.yaml
environment:
    import: environment-development.yaml
