version: "3.5"

networks:
  borat-network:
    driver: bridge
    name: borat-network

volumes:
  borat_redis_data:
    name: borat_redis_data

services:
  redis:
    container_name: redis
    image: redis
    networks: [ borat-network ]
    command:
      [
        "redis-server",
        "--port",
        "6379",
        "--save",
        "10",
        "1",
        "--loglevel",
        "warning"
      ]
    ports:
      - "6379:6379"
    volumes:
      - borat_redis_data:/data
  borat:
    build: .
    container_name: borat-redis
    image: borat-redis
    networks: [ borat-network ]
    ports:
      - "8080:8080"
    environment:
      BUCKET_NAME: ${BUCKET_NAME}
      PROJECT_ID: ${GCP_PROJECT}
      IMAGE_PATH: test.gif
      REDISHOST: redis
      REDISPORT: 6379
      GOOGLE_APPLICATION_CREDENTIALS: /config/application_default_credentials.json
    volumes:
      - ~/.config/gcloud/:/config
