schema_version: v1.0.0
environment:
    name: staging
    revision:
        type: branch
        identifier: pranay/VAN-3196
        repo: https://github.com/cldcvr/codepipes-tutorials
        dir: azure-functions/infra
        driver: github
    variables:
        - key: resource_group
          value: sls-seasi-dev-azure-funcs-rg
          type: tf_var
